calibrate_camera:
  ros__parameters:
    # Whether to run camera calibration online or not
    run_online: true
    # Where to save/load calibration data, relative to the source ada_ros2/ada_calibrate_camera
    data_dir: "data"
    # Where to save the calibration results, relative to the source folder ada_ros2/ada_calibrate_camera
    output_calib_name: config/calibs/auto.yaml
    # If run_online is false, this parameter specifies the folder to load data from
    offline_data_dir: "2024_10_09_21_12_30"

    # Charuco board parameters
    charuco_n_rows: 9
    charuco_n_cols: 14
    charuco_sq_length_m: 0.02 # 0.0351
    charuco_marker_length_m: 0.015 # 0.0257
    charuco_predefined_dictionary: 5  # https://docs.opencv.org/4.x/de/d67/group__objdetect__aruco.html#ga4e13135a118f497c6172311d601ce00d

    # Hand-eye calibration method
    hand_eye_calibration_method: 3  # https://docs.opencv.org/4.5.4/d9/d0c/group__calib3d.html#gad10a5ef12ee3499a0774c7904a801b99
