# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    jaco_arm_controller:
      type: force_gate_controller/ForceGateController


    jaco_arm_servo_controller:
      type: force_gate_controller/ForceGateVelocityController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    jaco_arm_cartesian_controller:
      type: cartesian_twist_controller/CartesianTwistController


    articulable_fork_controller:
      type: force_gate_controller/ForceGateController


    articulable_fork_cartesian_controller:
      type: cartesian_twist_controller/CartesianTwistController


jaco_arm_cartesian_controller:
    ros__parameters:
      end_effector_link: "j2n6s200_end_effector"
      robot_base_link: "j2n6s200_link_base"
      ik_solver: "selectively_damped_least_squares"
      joints:
        - j2n6s200_joint_1
        - j2n6s200_joint_2
        - j2n6s200_joint_3
        - j2n6s200_joint_4
        - j2n6s200_joint_5
        - j2n6s200_joint_6
      command_interfaces:
        - velocity
      wrench_threshold:
        topic: /wireless_ft/ftSensor3
        fMag: 1.0

jaco_arm_controller:
  ros__parameters:
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    stopped_velocity_tolerance: 0.01
    wrench_threshold:
      topic: /wireless_ft/ftSensor3
      fMag: 4.0
    gains: # Required because we're controlling a velocity interface
      j2n6s200_joint_1: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_2: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_3: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_4: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_5: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_6: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
    j2n6s200_joint_1:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_2:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_3:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_4:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_5:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_6:
      goal: 0.02
      trajectory: 0.05

jaco_arm_servo_controller:
  ros__parameters:
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
    wrench_threshold:
      topic: /wireless_ft/ftSensor3
      fMag: 1.0

articulable_fork_cartesian_controller:
    ros__parameters:
      end_effector_link: "forkTip"
      robot_base_link: "af_link_base"
      ik_solver: "selectively_damped_least_squares"
      joints:
        - af_joint_1
        - af_joint_2
      command_interfaces:
        - velocity

articulable_fork_controller:
  ros__parameters:
    joints:
      - af_joint_1
      - af_joint_2
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    stopped_velocity_tolerance: 0.01
    gains: # Required because we're controlling a velocity interface
      j2n6s200_joint_1: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_2: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_3: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_4: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_5: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
      j2n6s200_joint_6: {p: 4.0,  d: 0.0, i: 0.0, i_clamp: 1.0, normalize_error: true}
    af_joint_1:
      goal: 0.02
      trajectory: 0.05
    af_joint_2:
      goal: 0.02
      trajectory: 0.05

hand_controller:
  ros__parameters:
    joints:
      - j2n6s200_joint_finger_1
      - j2n6s200_joint_finger_2
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
    gains: # Required because we're controlling a velocity interface
      j2n6s200_joint_finger_1: {p: 1.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      j2n6s200_joint_finger_2: {p: 1.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
