# arm + gripper joint_state publisher
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

jaco_arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: [j2n6s200_joint_1, j2n6s200_joint_2, j2n6s200_joint_3,
    j2n6s200_joint_4, j2n6s200_joint_5, j2n6s200_joint_6]
  constraints:
    stopped_velocity_tolerance: 1.0
    j2n6s200_joint_1:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_2:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_3:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_4:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_5:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_6:
      goal: 0.02
      trajectory: 7
  gains: # Required because we're controlling a velocity interface
    j2n6s200_joint_1: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_2: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_3: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_4: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_5: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_6: {p: 3,  d: 0, i: 0, i_clamp: 1}